### ISSUE TITLE
"Warning: Illegal string offset" on Calendar page 

### ISSUE THREAD

**Issue by BBGuy** [kendraio/kendra_hub#53]
Warning: Illegal string offset 'data' in template_preprocess_calendar_month() (line 38 of /var/www/kendra/kendra-hub/dev/htdocs/sites/all/modules/contrib/calendar/theme/theme.inc).
Warning: Illegal string offset 'data' in template_preprocess_calendar_month() (line 43 of /var/www/kendra/kendra-hub/dev/htdocs/sites/all/modules/contrib/calendar/theme/theme.inc).

**Comment by andystiller** [comment]
I tried to reproduce the issue locally and it doesn't occur. After some research I found that it's a known issue for the Calendar module on PHP 5.4 https://www.drupal.org/node/1471400. The fix is to update the Calendar module to version 7.x-3.5.

**Comment by andystiller** [comment]
This is now fixed as part of issue #66. The Calendar module needed to be upgraded to to latest version.
