### ISSUE TITLE
User permission system

### ISSUE THREAD

**Issue by BBGuy** [kendraio/kendra_hub#55]
We currently have 4 types of users 
1) Not logged in - can only see login and register pages.
2) Visitor (registered user) – Can see all data but cant change any data.
3) Asset Author -  Can see all data, create new assets and edit those he created
4) Kendra admin - Can see and edit all data. 

This needs refinement especially the “see all data” part.
We also need to think of all the elements presented on the site and how should those be presented to the varies roles. Some of those elements are more mockups at this stage.

I would divide the functionality into three main parts:
1) Assets and contributions – The most developed part of the system
2) Legal entities, Right Type & Role Type – functional but all users can use and only admin can create – this needs more work to be fully functional.
3) Calender, Contacts, Notifications, Reports … - mockup early prototype stage

**Comment by BBGuy** [comment]
Also relevant notes can be added to #61

**Comment by dahacouk** [comment]
Looks good.

**Comment by BBGuy** [comment]
great Ill close for now. we will start a new issue wen this will need more work
