### ISSUE TITLE
Setting up Kendra Hub trial users...

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendra_hub#68]
- [ ] It doesn't seem right that a Kendra Hub trial user should be able to edit their own "Status" in their account:
http://hub.kendra.io/user/me/edit - substitute "me" for userid.

- [ ] "Asset actions" buttons are not displayed in a song view:
http://hub.kendra.io/content/stairway-heaven
* Add a contribution
* New Embedded Asset (sub clip)
* Embed a Sample

Any ideas?

**Comment by BBGuy** [comment]
all fixed
